#!/usr/bin/env php
<?php

require_once __DIR__ . '/server/init.php';
require_once __DIR__ . '/server/init_yii.php';

$config = require __DIR__ . '/src/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);

function exit_exception(int|string $status = 0): void
{
    exit($status);
}

function register_shutdown_function_user($callback, ...$args): void
{
    register_shutdown_function($callback, ...$args);
}
