#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/src/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);

function exit_exception(int|string $status = 0): void
{
    exit($status);
}

function register_shutdown_function_user($callback, ...$args): void
{
    register_shutdown_function($callback, ...$args);
}
